apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pico-agent

resources:
  - namespace.yaml
  - rbac.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/loafoe/pico-agent
    newTag: latest
