---
apiVersion: v1
kind: Service
metadata:
  name: pico-agent
  namespace: pico-agent
  labels:
    app.kubernetes.io/name: pico-agent
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: pico-agent
